# Site settings
title: Sau-Chin Chen's Website (alpha)
email: pmsp96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm testing the R packages to build and manage my blog
  through Rstudio.
baseurl: "/knitr-jekyll" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  SCgeeker
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
